name: ceo_hn7
description: CEO.HN7

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #animation
  animated_widgets: ^1.1.0
  animated_bottom_navigation_bar: ^1.2.0
  lottie: ^2.3.0
  flutter_staggered_animations: ^1.1.1
  # add Locale
  flutter_localizations:
    sdk: flutter

  #environment
  flutter_dotenv: ^5.0.2

  #app-update
  upgrader: 5.1.0
  #dropdownbutton:
  dropdown_button2: ^2.0.0
  flutter_switch: ^0.3.2
  #shimmer
  shimmer: ^2.0.0

  #image
  image_picker: ^0.8.5+3
  file_picker: ^5.2.5
  image_cropper: ^3.0.0

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  intl: ^0.18.0
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.1.0
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  #equatable: help us compare the state between two views -> prevent to rebuild the UI unnecessary.
  equatable: ^2.0.5
  #log interceptor
  pretty_dio_logger: ^1.1.1
  font_awesome_flutter: ^10.2.1
  page_transition: ^2.0.9
  cached_network_image: ^3.2.3

  #OAuth2 + openId
  flutter_appauth: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.2
  analyzer: ^5.7.1
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - app_config_product.env
    - app_config_test.env
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend-Regular.ttf

  #   - family: Quicksand
  #     fonts:
  #       - asset: assets/fonts/Quicksand-Regular.ttf
  #       - asset: assets/fonts/Quicksand-Medium.ttf
  #       - asset: assets/fonts/Quicksand-Light.ttf
  #       - asset: assets/fonts/Quicksand-Bold.ttf
  #       - asset: assets/fonts/Quicksand-SemiBold.ttf
